export const countries: Record<string, string> = {
  Afghanistan: "https://flagdom.com/flag-resources/flag-images/international/afghanistan/afghanistan-flag_3000x2000.png",
  Albania: "https://en.wikipedia.org/wiki/Flag_of_Albania#/media/File:Flag_of_Albania.svg",
  Algeria: "https://en.wikipedia.org/wiki/Flag_of_Algeria#/media/File:Flag_of_Algeria.svg",
  Andorra: "https://en.wikipedia.org/wiki/Flag_of_Andorra#/media/File:Flag_of_Andorra.svg",
  Angola: "https://en.wikipedia.org/wiki/Flag_of_Angola#/media/File:Flag_of_Angola.svg",
  "Antigua and Barbuda": "antigua-barbuda-url",
  Argentina: "argentina-url",
  Armenia: "https://cdn.britannica.com/11/4711-004-1504C169/Flag-Armenia.jpg",
  Australia: "https://cdn.britannica.com/78/6078-004-77AF7322/Flag-Australia.jpg",
  Austria: "austria-url",
  Azerbaijan: "azerbaijan-url",
  Bahamas: "bahamas-url",
  Bahrain: "bahrain-url",
  Bangladesh: "bangladesh-url",
  Barbados: "https://cdn.britannica.com/08/5108-004-FD58C8EF/Flag-Barbados.jpg",
  Belarus: "belarus-url",
  Belgium: "belgium-url",
  Belize: "belize-url",
  Benin: "benin-url",
  Bhutan: "bhutan-url",
  Bolivia: "bolivia-url",
  "Bosnia and Herzegovina": "bosnia-herzegovina-url",
  Botswana: "botswana-url",
  Brazil: "https://cdn.britannica.com/47/6847-004-7D668BB0/Flag-Brazil.jpg",
  Brunei: "brunei-url",
  Bulgaria: "bulgaria-url",
  "Burkina Faso": "burkina-faso-url",
  Burundi: "burundi-url",
  "Côte d'Ivoire": "cote-divoire-url",
  "Cabo Verde": "cabo-verde-url",
  Cambodia: "cambodia-url",
  Cameroon: "https://cdn.britannica.com/42/5042-004-7FF4ACCA/Flag-Cameroon.jpg",
  Canada: "https://cdn.britannica.com/68/7068-004-7848FEB4/Flag-Canada.jpg",
  "Central African Republic": "central-african-republic-url",
  Chad: "chad-url",
  Chile: "https://cdn.britannica.com/85/7485-004-00B07230/Flag-Chile.jpg",
  China: "https://cdn.britannica.com/90/7490-004-BAD4AA72/Flag-China.jpg",
  Colombia: "colombia-url",
  Comoros: "comoros-url",
  "Congo (Congo-Brazzaville)": "congo-brazzaville-url",
  "Costa Rica": "https://cdn.britannica.com/25/7225-004-65F33B16/Flag-Costa-Rica.jpg",
  Croatia: "croatia-url",
  Cuba: "https://cdn.britannica.com/10/5110-004-38075E57/Flag-Cuba.jpg",
  Cyprus: "cyprus-url",
  "Czech Republic": "https://cdn.britannica.com/86/7886-004-323985BD/Flag-Czech-Republic.jpg",
  "Democratic Republic of the Congo": "congo-democratic-url",
  Denmark: "https://cdn.britannica.com/07/8007-004-8CF0B1A9/Flag-Denmark.jpg",
  Djibouti: "djibouti-url",
  Dominica: "dominica-url",
  "Dominican Republic": "dominican-republic-url",
  Ecuador: "https://cdn.britannica.com/49/149-004-986E1BD8/flag-design-similarities-Ecuador-Colombia-flags-Venezuela.jpg",
  Egypt: "egypt-url",
  "El Salvador": "el-salvador-url",
  "Equatorial Guinea": "equatorial-guinea-url",
  Eritrea: "eritrea-url",
  Estonia: "estonia-url",
  Eswatini: "eswatini-url",
  Ethiopia: "ethiopia-url",
  Fiji: "fiji-url",
  Finland: "finland-url",
  France: "https://cdn.britannica.com/82/682-004-F0B47FCB/Flag-France.jpg",
  Gabon: "gabon-url",
  Gambia: "gambia-url",
  Georgia: "georgia-url",
  Germany: "https://cdn.britannica.com/97/897-004-232BDF01/Flag-Germany.jpg",
  Ghana: "https://cdn.britannica.com/54/5054-004-A09ABCDF/Flag-Ghana.jpg",
  Greece: "https://cdn.britannica.com/49/1049-004-AE4BAD3E/Flag-Greece.jpg",
  Grenada: "grenada-url",
  Guatemala: "guatemala-url",
  Guinea: "guinea-url",
  "Guinea-Bissau": "guinea-bissau-url",
  Guyana: "guyana-url",
  Haiti: "haiti-url",
  "Holy See": "holy-see-url",
  Honduras: "honduras-url",
  "Hong Kong": "https://cdn.britannica.com/43/82343-004-93844DE8/Flag-Hong-Kong-province-China.jpg",
  Hungary: "https://cdn.britannica.com/55/1455-004-5897143C/Flag-Hungary.jpg",
  Iceland: "iceland-url",
  India: "india-url",
  Indonesia: "indonesia-url",
  Iran: "iran-url",
  Iraq: "iraq-url",
  Ireland: "https://cdn.britannica.com/33/1733-004-5BA407D6/FLAG-Ireland.jpg",
  Israel: "https://cdn.britannica.com/53/1753-004-03582EDA/Flag-Israel.jpg",
  Italy: "https://cdn.britannica.com/59/1759-004-F4175463/Flag-Italy.jpg",
  Jamaica: "jamaica-url",
  Japan: "https://cdn.britannica.com/91/1791-004-DA3579A5/Flag-Japan.jpg",
  Jordan: "https://cdn.britannica.com/40/1840-004-718BA773/Flag-Jordan.jpg",
  Kazakhstan: "kazakhstan-url",
  Kenya: "kenya-url",
  Kiribati: "kiribati-url",
  Kuwait: "kuwait-url",
  Kyrgyzstan: "kyrgyzstan-url",
  Laos: "laos-url",
  Latvia: "latvia-url",
  Lebanon: "lebanon-url",
  Lesotho: "lesotho-url",
  Liberia: "liberia-url",
  Libya: "libya-url",
  Liechtenstein: "liechtenstein-url",
  Lithuania: "lithuania-url",
  Luxembourg: "luxembourg-url",
  Madagascar: "https://cdn.britannica.com/46/2246-004-17A6E838/Flag-Madagascar.jpg",
  Malawi: "malawi-url",
  Malaysia: "malaysia-url",
  Maldives: "maldives-url",
  Mali: "mali-url",
  Malta: "malta-url",
  "Marshall Islands": "marshall-islands-url",
  Mauritania: "mauritania-url",
  Mauritius: "mauritius-url",
  Mexico: "mexico-url",
  Micronesia: "micronesia-url",
  Moldova: "moldova-url",
  Monaco: "monaco-url",
  Mongolia: "mongolia-url",
  Montenegro: "montenegro-url",
  Morocco: "https://cdn.britannica.com/39/3039-004-52B064C7/Flag-Morocco.jpg",
  Mozambique: "mozambique-url",
  Myanmar: "myanmar-url",
  Namibia: "namibia-url",
  Nauru: "nauru-url",
  Nepal: "nepal-url",
  Netherlands: "https://cdn.britannica.com/82/2982-004-84A2A71E/flag-prototype-Netherlands-countries-European-flags.jpg",
  "New Zealand": "https://cdn.britannica.com/17/3017-004-DCC13F9D/Flag-New-Zealand.jpg",
  Nicaragua: "nicaragua-url",
  Niger: "niger-url",
  Nigeria: "nigeria-url",
  "North Korea": "north-korea-url",
  "North Macedonia": "north-macedonia-url",
  Norway: "norway-url",
  Oman: "oman-url",
  Pakistan: "pakistan-url",
  Palau: "palau-url",
  Palestine: "palestine-url",
  Panama: "panama-url",
  "Papua New Guinea": "papua-new-guinea-url",
  Paraguay: "paraguay-url",
  Peru: "peru-url",
  Philippines: "philippines-url",
  Poland: "poland-url",
  Portugal: "portugal-url",
  Qatar: "qatar-url",
  Romania: "romania-url",
  Russia: "russia-url",
  Rwanda: "rwanda-url",
  "Saint Kitts and Nevis": "saint-kitts-nevis-url",
  "Saint Lucia": "saint-lucia-url",
  "Saint Vincent and the Grenadines": "saint-vincent-grenadines-url",
  Samoa: "samoa-url",
  "San Marino": "san-marino-url",
  "Sao Tome and Principe": "sao-tome-principe-url",
  "Saudi Arabia": "saudi-arabia-url",
  Senegal: "senegal-url",
  Serbia: "serbia-url",
  Seychelles: "seychelles-url",
  "Sierra Leone": "sierra-leone-url",
  Singapore: "singapore-url",
  Slovakia: "slovakia-url",
  Slovenia: "slovenia-url",
  "Solomon Islands": "solomon-islands-url",
  Somalia: "somalia-url",
  "South Africa": "https://cdn.britannica.com/27/4227-004-32423B42/Flag-South-Africa.jpg",
  "South Korea": "https://cdn.britannica.com/49/1949-004-8818300C/Flag-South-Korea.jpg",
  "South Sudan": "south-sudan-url",
  Spain: "https://cdn.britannica.com/36/4336-004-6BD81071/Flag-Spain.jpg",
  "Sri Lanka": "sri-lanka-url",
  Sudan: "sudan-url",
  Suriname: "suriname-url",
  Sweden: "https://cdn.britannica.com/30/4530-004-1CF17E9C/Flag-Sweden.jpg",
  Switzerland: "switzerland-url",
  Syria: "syria-url",
  Tajikistan: "tajikistan-url",
  Tanzania: "https://cdn.britannica.com/20/20-004-EB20A026/Flag-Tanzania.jpg",
  Thailand: "thailand-url",
  "Timor-Leste": "timor-leste-url",
  Togo: "togo-url",
  Tonga: "tonga-url",
  "Trinidad and Tobago": "trinidad-tobago-url",
  Tunisia: "https://cdn.britannica.com/41/3041-004-F1D6DEFC/Flag-Tunisia.jpg",
  Turkey: "turkey-url",
  Turkmenistan: "turkmenistan-url",
  Tuvalu: "tuvalu-url",
  Uganda: "uganda-url",
  Ukraine: "ukraine-url",
  "United Arab Emirates": "united-arab-emirates-url",
  "United Kingdom": "https://cdn.britannica.com/25/4825-004-F1975B92/Flag-United-Kingdom.jpg",
  "United States of America": "united-states-url",
  Uruguay: "uruguay-url",
  Uzbekistan: "uzbekistan-url",
  Vanuatu: "vanuatu-url",
  Venezuela: "venezuela-url",
  Vietnam: "https://cdn.britannica.com/41/4041-004-D051B135/Flag-Vietnam.jpg",
  Yemen: "yemen-url",
  Zambia: "zambia-url",
  Zimbabwe: "zimbabwe-url",
}

// export const countries = [
//   "Afghanistan",
//   "Albania",
//   "Algeria",
//   "Andorra",
//   "Angola",
//   "Antigua and Barbuda",
//   "Argentina",
//   "Armenia",
//   "Australia",
//   "Austria",
//   "Azerbaijan",
//   "Bahamas",
//   "Bahrain",
//   "Bangladesh",
//   "Barbados",
//   "Belarus",
//   "Belgium",
//   "Belize",
//   "Benin",
//   "Bhutan",
//   "Bolivia",
//   "Bosnia and Herzegovina",
//   "Botswana",
//   "Brazil",
//   "Brunei",
//   "Bulgaria",
//   "Burkina Faso",
//   "Burundi",
//   "Côte d'Ivoire",
//   "Cabo Verde",
//   "Cambodia",
//   "Cameroon",
//   "Canada",
//   "Central African Republic",
//   "Chad",
//   "Chile",
//   "China",
//   "Colombia",
//   "Comoros",
//   "Congo (Congo-Brazzaville)",
//   "Costa Rica",
//   "Croatia",
//   "Cuba",
//   "Cyprus",
//   "Czechia (Czech Republic)",
//   "Democratic Republic of the Congo",
//   "Denmark",
//   "Djibouti",
//   "Dominica",
//   "Dominican Republic",
//   "Ecuador",
//   "Egypt",
//   "El Salvador",
//   "Equatorial Guinea",
//   "Eritrea",
//   "Estonia",
//   "Eswatini",
//   "Ethiopia",
//   "Fiji",
//   "Finland",
//   "France",
//   "Gabon",
//   "Gambia",
//   "Georgia",
//   "Germany",
//   "Ghana",
//   "Greece",
//   "Grenada",
//   "Guatemala",
//   "Guinea",
//   "Guinea-Bissau",
//   "Guyana",
//   "Haiti",
//   "Holy See",
//   "Honduras",
//   "Hungary",
//   "Iceland",
//   "India",
//   "Indonesia",
//   "Iran",
//   "Iraq",
//   "Ireland",
//   "Israel",
//   "Italy",
//   "Jamaica",
//   "Japan",
//   "Jordan",
//   "Kazakhstan",
//   "Kenya",
//   "Kiribati",
//   "Kuwait",
//   "Kyrgyzstan",
//   "Laos",
//   "Latvia",
//   "Lebanon",
//   "Lesotho",
//   "Liberia",
//   "Libya",
//   "Liechtenstein",
//   "Lithuania",
//   "Luxembourg",
//   "Madagascar",
//   "Malawi",
//   "Malaysia",
//   "Maldives",
//   "Mali",
//   "Malta",
//   "Marshall Islands",
//   "Mauritania",
//   "Mauritius",
//   "Mexico",
//   "Micronesia",
//   "Moldova",
//   "Monaco",
//   "Mongolia",
//   "Montenegro",
//   "Morocco",
//   "Mozambique",
//   "Myanmar",
//   "Namibia",
//   "Nauru",
//   "Nepal",
//   "Netherlands",
//   "New Zealand",
//   "Nicaragua",
//   "Niger",
//   "Nigeria",
//   "North Korea",
//   "North Macedonia",
//   "Norway",
//   "Oman",
//   "Pakistan",
//   "Palau",
//   "Palestine",
//   "Panama",
//   "Papua New Guinea",
//   "Paraguay",
//   "Peru",
//   "Philippines",
//   "Poland",
//   "Portugal",
//   "Qatar",
//   "Romania",
//   "Russia",
//   "Rwanda",
//   "Saint Kitts and Nevis",
//   "Saint Lucia",
//   "Saint Vincent and the Grenadines",
//   "Samoa",
//   "San Marino",
//   "Sao Tome and Principe",
//   "Saudi Arabia",
//   "Senegal",
//   "Serbia",
//   "Seychelles",
//   "Sierra Leone",
//   "Singapore",
//   "Slovakia",
//   "Slovenia",
//   "Solomon Islands",
//   "Somalia",
//   "South Africa",
//   "South Korea",
//   "South Sudan",
//   "Spain",
//   "Sri Lanka",
//   "Sudan",
//   "Suriname",
//   "Sweden",
//   "Switzerland",
//   "Syria",
//   "Tajikistan",
//   "Tanzania",
//   "Thailand",
//   "Timor-Leste",
//   "Togo",
//   "Tonga",
//   "Trinidad and Tobago",
//   "Tunisia",
//   "Turkey",
//   "Turkmenistan",
//   "Tuvalu",
//   "Uganda",
//   "Ukraine",
//   "United Arab Emirates",
//   "United Kingdom",
//   "United States of America",
//   "Uruguay",
//   "Uzbekistan",
//   "Vanuatu",
//   "Venezuela",
//   "Vietnam",
//   "Yemen",
//   "Zambia",
//   "Zimbabwe",
// ];
