const RecommendedData = [
    {
        id: 1,
        name: "King's College Health and Society Program",
        country: "London, UK",
        term: "Fall 2024, Spring 2024",
        description: "Description 1",
        image: "https://cdn.britannica.com/25/4825-004-F1975B92/Flag-United-Kingdom.jpg",
      },
      {
        id: 2,
        name: "Brown Global Program / CASA Dublin",
        country: "Dublin, Ireland",
        term: "Fall 2024, Full Year 2024-2025",
        description: "Description 2",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/255px-Flag_of_Ireland.svg.png",
      },
      {
        id: 3,
        name: "Inter-University Program for Chinese Language Studies (IUP)",
        country: "Beijing, China",
        term: "Fall 2024, Spring 2024",
        description: "Description 3",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/2560px-Flag_of_the_People%27s_Republic_of_China.svg.png",
      },
      {
        id: 2,
        name: "Brown Global Program / CASA Dublin",
        country: "Dublin, Ireland",
        term: "Fall 2024, Full Year 2024-2025",
        description: "Description 2",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/255px-Flag_of_Ireland.svg.png",
      },
      {
        id: 2,
        name: "Brown Global Program / CASA Dublin",
        country: "Dublin, Ireland",
        term: "Fall 2024, Full Year 2024-2025",
        description: "Description 2",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/255px-Flag_of_Ireland.svg.png",
      },
      {
        id: 2,
        name: "Brown Global Program / CASA Dublin",
        country: "Dublin, Ireland",
        term: "Fall 2024, Full Year 2024-2025",
        description: "Description 2",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/255px-Flag_of_Ireland.svg.png",
      },
      {
        id: 2,
        name: "Brown Global Program / CASA Dublin",
        country: "Dublin, Ireland",
        term: "Fall 2024, Full Year 2024-2025",
        description: "Description 2",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/255px-Flag_of_Ireland.svg.png",
      },
  ];

  export default RecommendedData;